id: opecha:P000001
initial_creation_type: input
source_metadata:
  id: bdr:W2KG210295
  title: བཀའ་འགྱུར། ༼ཕུག་བྲག་བྲིས་མ༽
  publication:
  author: ''

layers:
  - index
  - pagination
  - correction
  - peydurma-note
  - uncertain
 
 views:
    temporary:
      loc: releases/tag/temp
      layers:
        - toc
        - page # page-index in boyig
        - correction
      format:
        - epub
    publication:
      loc: tree/publication
      layers:
        - toc
        - page # page-index in boyig
        - correction
      format:
        - hfml
    diplomatic:
      loc: tree/diplomatic
      layers:
        - page # page-index in boyig
        - uncertain
      format:
        - hfml
       
